
language: generic
services:
  - docker

notifications:
  email:
    on_success: change
    on_failure: always
env:
  global:
    - ROS_REPO=ros
    - NOT_TEST_INSTALL=true
  matrix:
    - ROS_DISTRO=eloquent UPSTREAM_WORKSPACE=debian
    - ROS_DISTRO=foxy UPSTREAM_WORKSPACE=debian
matrix:
  allow_failures:
    - env: ROS_DISTRO=foxy UPSTREAM_WORKSPACE=debian
install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
script:
  - .industrial_ci/travis.sh
#  - ./travis.sh  # Enable this when you have a package-local script
